package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"strconv"

	"last-go/internal/auth"

	"golang.org/x/crypto/bcrypt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthResponse, error) {
	// Check if user already exists
	existingUser, err := r.DB.GetUserByEmail(input.Email)
	if err == nil && existingUser != nil {
		return nil, errors.New("user with this email already exists")
	}

	// Create new user
	user, err := r.DB.CreateUser(input.Email, input.Username, input.Password)
	if err != nil {
		return nil, err
	}

	// Generate JWT token
	token, err := auth.GenerateToken(strconv.Itoa(user.ID), user.Email)
	if err != nil {
		return nil, err
	}

	return &AuthResponse{
		User: &User{
			ID:        strconv.Itoa(user.ID),
			Email:     user.Email,
			Username:  user.Username,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		},
		Token: token,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthResponse, error) {
	// Get user by email
	user, err := r.DB.GetUserByEmail(input.Email)
	if err != nil {
		return nil, errors.New("invalid credentials")
	}

	// Check password
	err = bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password))
	if err != nil {
		return nil, errors.New("invalid credentials")
	}

	// Generate JWT token
	token, err := auth.GenerateToken(strconv.Itoa(user.ID), user.Email)
	if err != nil {
		return nil, err
	}

	return &AuthResponse{
		User: &User{
			ID:        strconv.Itoa(user.ID),
			Email:     user.Email,
			Username:  user.Username,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		},
		Token: token,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	// Get user from context (set by middleware)
	userIDStr, ok := ctx.Value("userID").(string)
	if !ok {
		return nil, errors.New("not authenticated")
	}
	userID, err := strconv.Atoi(userIDStr)
	if err != nil {
		return nil, errors.New("invalid user id in context")
	}

	user, err := r.DB.GetUserByID(userID)
	if err != nil {
		return nil, err
	}

	return &User{
		ID:        strconv.Itoa(user.ID),
		Email:     user.Email,
		Username:  user.Username,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	users, err := r.DB.GetAllUsers()
	if err != nil {
		return nil, err
	}

	var graphqlUsers []*User
	for _, user := range users {
		graphqlUsers = append(graphqlUsers, &User{
			ID:        strconv.Itoa(user.ID),
			Email:     user.Email,
			Username:  user.Username,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		})
	}

	return graphqlUsers, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
